// MarketData exposes the mark-price feed the web process already maintains.
//
// It is deliberately read-only and deliberately small: two RPCs, one unary and
// one server-streaming, both served from the SAME in-process ticker hub that
// feeds /api/stream/tickers (cmd/web/stream.go). A gRPC caller and an SSE
// browser tab therefore see the same numbers from the same upstream
// connection — gRPC is a second TRANSPORT, not a second data path.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: marketdata/v1/marketdata.proto

package marketdatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMarkPriceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short ticker as the UI uses it: "BTC", "ETH", "XAU". Case-insensitive.
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarkPriceRequest) Reset() {
	*x = GetMarkPriceRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarkPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarkPriceRequest) ProtoMessage() {}

func (x *GetMarkPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarkPriceRequest.ProtoReflect.Descriptor instead.
func (*GetMarkPriceRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarkPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Wrapped rather than returning MarkPrice directly so a later field (the
// upstream health the hub already tracks, say) is an additive change.
type GetMarkPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *MarkPrice             `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarkPriceResponse) Reset() {
	*x = GetMarkPriceResponse{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarkPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarkPriceResponse) ProtoMessage() {}

func (x *GetMarkPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarkPriceResponse.ProtoReflect.Descriptor instead.
func (*GetMarkPriceResponse) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarkPriceResponse) GetPrice() *MarkPrice {
	if x != nil {
		return x.Price
	}
	return nil
}

type StreamMarkPricesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Symbols to follow. EMPTY MEANS ALL symbols the hub carries.
	Symbols       []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMarkPricesRequest) Reset() {
	*x = StreamMarkPricesRequest{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarkPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarkPricesRequest) ProtoMessage() {}

func (x *StreamMarkPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarkPricesRequest.ProtoReflect.Descriptor instead.
func (*StreamMarkPricesRequest) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *StreamMarkPricesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type MarkPrice struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price  float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	// true  = the price came off the exchange mark-price websocket (~1 Hz).
	// false = websocket has not delivered this symbol yet, so the value is the
	//         30s REST snapshot. The hub degrades per-symbol, so this is a
	//         per-symbol fact, not a connection-wide one.
	Live bool `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	// Server time at which this value was fanned out. The hub does not carry an
	// exchange timestamp, so this is NOT exchange time — see docs/grpc.md.
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPrice) Reset() {
	*x = MarkPrice{}
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPrice) ProtoMessage() {}

func (x *MarkPrice) ProtoReflect() protoreflect.Message {
	mi := &file_marketdata_v1_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPrice.ProtoReflect.Descriptor instead.
func (*MarkPrice) Descriptor() ([]byte, []int) {
	return file_marketdata_v1_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *MarkPrice) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarkPrice) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarkPrice) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *MarkPrice) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

var File_marketdata_v1_marketdata_proto protoreflect.FileDescriptor

const file_marketdata_v1_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x1emarketdata/v1/marketdata.proto\x12\x18tradingbot.marketdata.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x13GetMarkPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"Q\n" +
	"\x14GetMarkPriceResponse\x129\n" +
	"\x05price\x18\x01 \x01(\v2#.tradingbot.marketdata.v1.MarkPriceR\x05price\"3\n" +
	"\x17StreamMarkPricesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"~\n" +
	"\tMarkPrice\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x12\n" +
	"\x04live\x18\x03 \x01(\bR\x04live\x12/\n" +
	"\x05as_of\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf2\xe9\x01\n" +
	"\n" +
	"MarketData\x12m\n" +
	"\fGetMarkPrice\x12-.tradingbot.marketdata.v1.GetMarkPriceRequest\x1a..tradingbot.marketdata.v1.GetMarkPriceResponse\x12l\n" +
	"\x10StreamMarkPrices\x121.tradingbot.marketdata.v1.StreamMarkPricesRequest\x1a#.tradingbot.marketdata.v1.MarkPrice0\x01BEZCgithub.com/henry190927/trading-bot/proto/marketdata/v1;marketdatav1b\x06proto3"

var (
	file_marketdata_v1_marketdata_proto_rawDescOnce sync.Once
	file_marketdata_v1_marketdata_proto_rawDescData []byte
)

func file_marketdata_v1_marketdata_proto_rawDescGZIP() []byte {
	file_marketdata_v1_marketdata_proto_rawDescOnce.Do(func() {
		file_marketdata_v1_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketdata_v1_marketdata_proto_rawDesc), len(file_marketdata_v1_marketdata_proto_rawDesc)))
	})
	return file_marketdata_v1_marketdata_proto_rawDescData
}

var file_marketdata_v1_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketdata_v1_marketdata_proto_goTypes = []any{
	(*GetMarkPriceRequest)(nil),     // 0: tradingbot.marketdata.v1.GetMarkPriceRequest
	(*GetMarkPriceResponse)(nil),    // 1: tradingbot.marketdata.v1.GetMarkPriceResponse
	(*StreamMarkPricesRequest)(nil), // 2: tradingbot.marketdata.v1.StreamMarkPricesRequest
	(*MarkPrice)(nil),               // 3: tradingbot.marketdata.v1.MarkPrice
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_marketdata_v1_marketdata_proto_depIdxs = []int32{
	3, // 0: tradingbot.marketdata.v1.GetMarkPriceResponse.price:type_name -> tradingbot.marketdata.v1.MarkPrice
	4, // 1: tradingbot.marketdata.v1.MarkPrice.as_of:type_name -> google.protobuf.Timestamp
	0, // 2: tradingbot.marketdata.v1.MarketData.GetMarkPrice:input_type -> tradingbot.marketdata.v1.GetMarkPriceRequest
	2, // 3: tradingbot.marketdata.v1.MarketData.StreamMarkPrices:input_type -> tradingbot.marketdata.v1.StreamMarkPricesRequest
	1, // 4: tradingbot.marketdata.v1.MarketData.GetMarkPrice:output_type -> tradingbot.marketdata.v1.GetMarkPriceResponse
	3, // 5: tradingbot.marketdata.v1.MarketData.StreamMarkPrices:output_type -> tradingbot.marketdata.v1.MarkPrice
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_marketdata_v1_marketdata_proto_init() }
func file_marketdata_v1_marketdata_proto_init() {
	if File_marketdata_v1_marketdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketdata_v1_marketdata_proto_rawDesc), len(file_marketdata_v1_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketdata_v1_marketdata_proto_goTypes,
		DependencyIndexes: file_marketdata_v1_marketdata_proto_depIdxs,
		MessageInfos:      file_marketdata_v1_marketdata_proto_msgTypes,
	}.Build()
	File_marketdata_v1_marketdata_proto = out.File
	file_marketdata_v1_marketdata_proto_goTypes = nil
	file_marketdata_v1_marketdata_proto_depIdxs = nil
}
