// MarketData exposes the mark-price feed the web process already maintains.
//
// It is deliberately read-only and deliberately small: two RPCs, one unary and
// one server-streaming, both served from the SAME in-process ticker hub that
// feeds /api/stream/tickers (cmd/web/stream.go). A gRPC caller and an SSE
// browser tab therefore see the same numbers from the same upstream
// connection — gRPC is a second TRANSPORT, not a second data path.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: marketdata/v1/marketdata.proto

package marketdatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketData_GetMarkPrice_FullMethodName     = "/tradingbot.marketdata.v1.MarketData/GetMarkPrice"
	MarketData_StreamMarkPrices_FullMethodName = "/tradingbot.marketdata.v1.MarketData/StreamMarkPrices"
)

// MarketDataClient is the client API for MarketData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketDataClient interface {
	// GetMarkPrice returns the newest mark price for one symbol.
	//
	// Errors: INVALID_ARGUMENT (empty symbol), NOT_FOUND (symbol is not in the
	// hub's universe), UNAVAILABLE (symbol known but no price yet),
	// DEADLINE_EXCEEDED (hub had no snapshot before the deadline).
	GetMarkPrice(ctx context.Context, in *GetMarkPriceRequest, opts ...grpc.CallOption) (*GetMarkPriceResponse, error)
	// StreamMarkPrices pushes a MarkPrice every time that symbol's price
	// changes. The stream ends when the client cancels, when the deadline
	// expires, or when the server drains for shutdown (UNAVAILABLE).
	StreamMarkPrices(ctx context.Context, in *StreamMarkPricesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarkPrice], error)
}

type marketDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataClient(cc grpc.ClientConnInterface) MarketDataClient {
	return &marketDataClient{cc}
}

func (c *marketDataClient) GetMarkPrice(ctx context.Context, in *GetMarkPriceRequest, opts ...grpc.CallOption) (*GetMarkPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarkPriceResponse)
	err := c.cc.Invoke(ctx, MarketData_GetMarkPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataClient) StreamMarkPrices(ctx context.Context, in *StreamMarkPricesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarkPrice], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[0], MarketData_StreamMarkPrices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMarkPricesRequest, MarkPrice]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamMarkPricesClient = grpc.ServerStreamingClient[MarkPrice]

// MarketDataServer is the server API for MarketData service.
// All implementations must embed UnimplementedMarketDataServer
// for forward compatibility.
type MarketDataServer interface {
	// GetMarkPrice returns the newest mark price for one symbol.
	//
	// Errors: INVALID_ARGUMENT (empty symbol), NOT_FOUND (symbol is not in the
	// hub's universe), UNAVAILABLE (symbol known but no price yet),
	// DEADLINE_EXCEEDED (hub had no snapshot before the deadline).
	GetMarkPrice(context.Context, *GetMarkPriceRequest) (*GetMarkPriceResponse, error)
	// StreamMarkPrices pushes a MarkPrice every time that symbol's price
	// changes. The stream ends when the client cancels, when the deadline
	// expires, or when the server drains for shutdown (UNAVAILABLE).
	StreamMarkPrices(*StreamMarkPricesRequest, grpc.ServerStreamingServer[MarkPrice]) error
	mustEmbedUnimplementedMarketDataServer()
}

// UnimplementedMarketDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServer struct{}

func (UnimplementedMarketDataServer) GetMarkPrice(context.Context, *GetMarkPriceRequest) (*GetMarkPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarkPrice not implemented")
}
func (UnimplementedMarketDataServer) StreamMarkPrices(*StreamMarkPricesRequest, grpc.ServerStreamingServer[MarkPrice]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarkPrices not implemented")
}
func (UnimplementedMarketDataServer) mustEmbedUnimplementedMarketDataServer() {}
func (UnimplementedMarketDataServer) testEmbeddedByValue()                    {}

// UnsafeMarketDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServer will
// result in compilation errors.
type UnsafeMarketDataServer interface {
	mustEmbedUnimplementedMarketDataServer()
}

func RegisterMarketDataServer(s grpc.ServiceRegistrar, srv MarketDataServer) {
	// If the following call pancis, it indicates UnimplementedMarketDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketData_ServiceDesc, srv)
}

func _MarketData_GetMarkPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarkPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServer).GetMarkPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketData_GetMarkPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServer).GetMarkPrice(ctx, req.(*GetMarkPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketData_StreamMarkPrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMarkPricesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).StreamMarkPrices(m, &grpc.GenericServerStream[StreamMarkPricesRequest, MarkPrice]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketData_StreamMarkPricesServer = grpc.ServerStreamingServer[MarkPrice]

// MarketData_ServiceDesc is the grpc.ServiceDesc for MarketData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradingbot.marketdata.v1.MarketData",
	HandlerType: (*MarketDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarkPrice",
			Handler:    _MarketData_GetMarkPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarkPrices",
			Handler:       _MarketData_StreamMarkPrices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marketdata/v1/marketdata.proto",
}
